### ISSUE TITLE
fit-line not working

### ISSUE THREAD

**Issue by rala72** [pikselinweb/ngx-fittext#15]
I tried to migrate from [joseph-montanez/angular-fittext](https://github.com/joseph-montanez/angular-fittext) during my Angular 12 upgrade, but I didn't get it to work.

I checked the demo page and on Windows 10 Chrome 98.0.4758.102 it is not working.

Not sure what I can provide, so I just added a screenshot of the `Simple Usage` for now.

![image](https://user-images.githubusercontent.com/6838669/156433840-3d9fb28d-245c-4d69-bfc9-d106942acd2d.png)

**Comment by pikselinweb** [comment]
Hi. Simple usage fit text on page load. Did you resize the page? If you want to fit when window resize you need to  set calcOnResize true, by the default it is false.
![image](https://user-images.githubusercontent.com/11332774/156834570-b6002bbb-c826-44a6-88a7-3ff374ef391a.png)

**Comment by rala72** [comment]
fair enough, the example seems to work
I guess I had another problem on my project, and I'll open another ticket if I need one

Maybe you could enable the resize on reload at the demo, because this would probably a frequently used feature and nice/easy to show on the demo
