### ISSUE TITLE
Cannot read properties of undefined (reading 'unsubscribe')

### ISSUE THREAD

**Issue by Abdelrahman-7gab** [pikselinweb/ngx-fittext#19]
I'm using this library in cards generated from a JSON file coming from the backend. 
when changing the search query the data changes and thus changing the cards where the title uses this library to fit the text to the card. 
however when the data changes and now each card should be destroyed and generate new cards 
I face this error
 Cannot read properties of undefined (reading 'unsubscribe')
![image](https://user-images.githubusercontent.com/63824808/174149579-b51609e7-e9e0-4f41-8d34-e2541490ff29.png)
I use an *ngfor loop to loop through the data and generate cards.

**Comment by Abdelrahman-7gab** [comment]
after reading a little bit in the code. 
The error occurs because the subscription is only created if calcOnResize is true. 
so passing calcOnResize to the component fixed the issue.

however this issue is easily fixable with an if condition to avoid unsubscribing when calcOnResize is not passed or is false.

**Comment by pikselinweb** [comment]
Hi Abdelrahman. I am sorry to hear this problem. I wish to fix it but i am too busy with work and life by trying to save my live standards against high inflation. Honestly it is hard to spend time for fix it in this period. Thank you for submit this issue.
